config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"
  get 'search/autocomplete' => "search#autocomplete", as: :search_autocomplete

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  # Get all keys of user
  get ':username.keys' => 'profiles/keys#get_keys' , constraints: { username: /.*/ }

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitlab_shell.repos_path,
    upload_pack:  Gitlab.config.gitlab_shell.upload_pack,
    receive_pack: Gitlab.config.gitlab_shell.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }, via: [:get, :post]

  #
  # Help
  #

  get 'help'                  => 'help#index'
  get 'help/:category/:file'  => 'help#show', as: :help_page
  get 'help/shortcuts'

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Explroe area
  #
  namespace :explore do
    resources :projects, only: [:index] do
      collection do
        get :trending
        get :starred
      end
    end

    resources :groups, only: [:index]
    root to: "projects#trending"
  end

  # Compatibility with old routing
  get 'public' => "explore/projects#index"
  get 'public/projects' => "explore/projects#index"

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :team_update
        put :block
        put :unblock
        delete 'remove/:email_id', action: 'remove_email', as: 'remove_email'
      end
    end

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_teams_update
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resources :broadcast_messages, only: [:index, :create, :destroy]
    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]

    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do
      member do
        put :transfer
      end
    end

    root to: "dashboard#index"
  end

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :history
      get :design

      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :account, only: [:show, :update]
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create, :edit, :update] do
        member do
          put :reset
        end
      end
      resources :keys
      resources :emails, only: [:index, :create, :destroy]
      resources :groups, only: [:index] do
        member do
          delete :leave
        end
      end
      resource :avatar, only: [:destroy]
    end
  end

  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }, via: :get

  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard", only: [:show] do
    member do
      get :projects
      get :issues
      get :merge_requests
    end
  end

  #
  # Groups Area
  #
  resources :groups, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}  do
    member do
      get :issues
      get :merge_requests
      get :members
      get :projects
    end

    scope module: :groups do
      resources :group_members, only: [:create, :update, :destroy]
      resource :avatar, only: [:destroy]
      resources :milestones
    end
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations , passwords: :passwords, sessions: :sessions, confirmations: :confirmations }

  devise_scope :user do
    get "/users/auth/:provider/omniauth_error" => "omniauth_callbacks#omniauth_error", as: :omniauth_error
  end
  #
  # Project Area
  #
  resources :projects, constraints: { id: /[a-zA-Z.0-9_\-]+\/[a-zA-Z.0-9_\-]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      put :transfer
      post :fork
      post :archive
      post :unarchive
      post :upload_image
      post :toggle_star
      get :autocomplete_sources
      get :import
      put :retry_import
    end

    scope module: :projects do
      resources :blob, only: [:show, :destroy], constraints: { id: /.+/ } do
        get :diff, on: :member
      end
      resources :raw,       only: [:show], constraints: {id: /.+/}
      resources :tree,      only: [:show], constraints: {id: /.+/, format: /(html|js)/ }
      resources :edit_tree, only: [:show, :update], constraints: { id: /.+/ }, path: 'edit' do
        post :preview, on: :member
      end
      resources :new_tree,  only: [:show, :update], constraints: {id: /.+/}, path: 'new'
      resources :commit,    only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
      resources :commits,   only: [:show], constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}
      resources :compare,   only: [:index, :create]
      resources :blame,     only: [:show], constraints: {id: /.+/}
      resources :network,   only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
      resources :graphs,    only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/} do
        member do
          get :commits
        end
      end

      match "/compare/:from...:to" => "compare#show", as: "compare", via: [:get, :post], constraints: {from: /.+/, to: /.+/}

        resources :snippets, constraints: {id: /\d+/} do
          member do
            get "raw"
          end
        end

      resources :wikis, only: [:show, :edit, :destroy, :create], constraints: {id: /[a-zA-Z.0-9_\-\/]+/} do
        collection do
          get :pages
          put ':id' => 'wikis#update'
          get :git_access
        end

        member do
          get "history"
        end
      end

      resource :repository, only: [:show] do
        member do
          get "archive", constraints: { format: Gitlab::Regex.archive_formats_regex }
        end
      end

      resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
        member do
          get :test
        end
      end

      resources :deploy_keys, constraints: {id: /\d+/} do
        member do
          put :enable
          put :disable
        end
      end

      resources :branches, only: [:index, :new, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex }
      resources :tags, only: [:index, :new, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex }
      resources :protected_branches, only: [:index, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex }

      resources :refs, only: [] do
        collection do
          get "switch"
        end

        member do
          # tree viewer logs
          get "logs_tree", constraints: { id: Gitlab::Regex.git_reference_regex }
          get "logs_tree/:path" => "refs#logs_tree",
            as: :logs_file,
            constraints: {
              id:   Gitlab::Regex.git_reference_regex,
              path: /.*/
            }
        end
      end

      resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
        member do
          get :diffs
          post :automerge
          get :automerge_check
          get :ci_status
        end

        collection do
          get :branch_from
          get :branch_to
          get :update_branches
        end
      end

      resources :hooks, only: [:index, :create, :destroy], constraints: {id: /\d+/} do
        member do
          get :test
        end
      end

      resources :team, controller: 'team_members', only: [:index]
      resources :milestones, except: [:destroy], constraints: {id: /\d+/} do
        member do
          put :sort_issues
          put :sort_merge_requests
        end
      end

      resources :labels, constraints: {id: /\d+/} do
        collection do
          post :generate
        end
      end

      resources :issues, constraints: {id: /\d+/}, except: [:destroy] do
        collection do
          post  :bulk_update
        end
      end

      resources :team_members, except: [:index, :edit], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ } do
        collection do
          delete :leave

          # Used for import team
          # from another project
          get :import
          post :apply_import
        end
      end

      resources :notes, only: [:index, :create, :destroy, :update], constraints: {id: /\d+/} do
        member do
          delete :delete_attachment
        end

        collection do
          post :preview
        end
      end
    end
  end

  get ':id' => "namespaces#show", constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}

  root to: "dashboard#show"
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::ApplicationController
  before_filter :group, only: [:edit, :show, :update, :destroy, :project_update, :project_teams_update]

  def index
    @groups = Group.order('name ASC')
    @groups = @groups.search(params[:name]) if params[:name].present?
    @groups = @groups.page(params[:page]).per(20)
  end

  def show
    @members = @group.members.order("access_level DESC").page(params[:members_page]).per(30)
    @projects = @group.projects.page(params[:projects_page]).per(30)
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group.path = @group.name.dup.parameterize if @group.name

    if @group.save
      @group.add_owner(current_user)
      redirect_to [:admin, @group], notice: 'Group was successfully created.'
    else
      render "new"
    end
  end

  def update
    if @group.update_attributes(group_params)
      redirect_to [:admin, @group], notice: 'Group was successfully updated.'
    else
      render "edit"
    end
  end

  def project_teams_update
    @group.add_users(params[:user_ids].split(','), params[:access_level])

    redirect_to [:admin, @group], notice: 'Users were successfully added.'
  end

  def destroy
    @group.destroy

    redirect_to admin_groups_path, notice: 'Group was successfully deleted.'
  end

  private

  def group
    @group = Group.find_by(path: params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :description, :path, :avatar)
  end
end

app/controllers/explore/groups_controller.rb
class Explore::GroupsController < ApplicationController
  skip_before_filter :authenticate_user!,
                     :reject_blocked, :set_current_user_for_observers,
                     :add_abilities

  layout "explore"

  def index
    @groups = GroupsFinder.new.execute(current_user)
    @groups = @groups.search(params[:search]) if params[:search].present?
    @groups = @groups.sort(@sort = params[:sort])
    @groups = @groups.page(params[:page]).per(20)
  end
end

app/controllers/groups/avatars_controller.rb
class Groups::AvatarsController < ApplicationController
  layout "profile"

  def destroy
    @group = Group.find_by(path: params[:group_id])
    @group.remove_avatar!

    @group.save

    redirect_to edit_group_path(@group)
  end
end

app/controllers/groups/group_members_controller.rb
class Groups::GroupMembersController < ApplicationController
  before_filter :group

  # Authorize
  before_filter :authorize_admin_group!

  layout 'group'

  def create
    @group.add_users(params[:user_ids].split(','), params[:access_level])

    redirect_to members_group_path(@group), notice: 'Users were successfully added.'
  end

  def update
    @member = @group.group_members.find(params[:id])
    @member.update_attributes(member_params)
  end

  def destroy
    @users_group = @group.group_members.find(params[:id])

    if can?(current_user, :destroy, @users_group)  # May fail if last owner.
      @users_group.destroy
      respond_to do |format|
        format.html { redirect_to members_group_path(@group), notice: 'User was  successfully removed from group.' }
        format.js { render nothing: true }
      end
    else
      return render_403
    end
  end

  protected

  def group
    @group ||= Group.find_by(path: params[:group_id])
  end

  def authorize_admin_group!
    unless can?(current_user, :manage_group, group)
      return render_404
    end
  end

  def member_params
    params.require(:group_member).permit(:access_level, :user_id)
  end
end

app/controllers/groups/milestones_controller.rb
class Groups::MilestonesController < ApplicationController
  layout 'group'

  before_filter :authorize_group_milestone!, only: :update

  def index
    project_milestones = case params[:status]
                         when 'all'; status
                         when 'closed'; status('closed')
                         else status('active')
                         end
    @group_milestones = Milestones::GroupService.new(project_milestones).execute
    @group_milestones = Kaminari.paginate_array(@group_milestones).page(params[:page]).per(30)
  end

  def show
    project_milestones = Milestone.where(project_id: group.projects).order("due_date ASC")
    @group_milestone = Milestones::GroupService.new(project_milestones).milestone(title)
  end

  def update
    project_milestones = Milestone.where(project_id: group.projects).order("due_date ASC")
    @group_milestones = Milestones::GroupService.new(project_milestones).milestone(title)

    @group_milestones.milestones.each do |milestone|
      Milestones::UpdateService.new(milestone.project, current_user, params[:milestone]).execute(milestone)
    end

    respond_to do |format|
      format.js
      format.html do
        redirect_to group_milestones_path(group)
      end
    end
  end

  private

  def group
    @group ||= Group.find_by(path: params[:group_id])
  end

  def title
    params[:title]
  end

  def status(state = nil)
    conditions = { project_id: group.projects }
    conditions.reverse_merge!(state: state) if state
    Milestone.where(conditions).order("title ASC")
  end

  def authorize_group_milestone!
    return render_404 unless can?(current_user, :manage_group, group)
  end
end

app/controllers/profiles/groups_controller.rb
class Profiles::GroupsController < ApplicationController
  layout "profile"

  def index
    @user_groups = current_user.group_members.page(params[:page]).per(20)
  end

  def leave
    @users_group = group.group_members.where(user_id: current_user.id).first
    if can?(current_user, :destroy, @users_group)
      @users_group.destroy
      redirect_to(profile_groups_path, info: "You left #{group.name} group.")
    else
      return render_403
    end
  end

  private

  def group
    @group ||= Group.find_by(path: params[:id])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def remove_user_from_group_message(group, user)
    "Are you sure you want to remove \"#{user.name}\" from \"#{group.name}\"?"
  end

  def leave_group_message(group)
    "Are you sure you want to leave \"#{group}\" group?"
  end
  
  def should_user_see_group_roles?(user, group)
    if user
      user.is_admin? || group.members.exists?(user_id: user.id)
    else
      false
    end
  end

  def group_head_title
    title = @group.name

    title = if current_action?(:issues)
              "Issues - " + title
            elsif current_action?(:merge_requests)
              "Merge requests - " + title
            elsif current_action?(:members)
              "Members - " + title
            elsif current_action?(:edit)
              "Settings - " + title
            else
              title
            end

    title
  end

  def group_filter_path(entity, options={})
    exist_opts = {
      status: params[:status]
    }

    options = exist_opts.merge(options)

    path = request.path
    path << "?#{options.to_param}"
    path
  end
end

app/views/groups/_filter.html.haml
= form_tag group_filter_path(entity), method: 'get' do
  %fieldset
    %ul.nav.nav-pills.nav-stacked
      %li{class: ("active" if (params[:status] == 'active' || !params[:status]))}
        = link_to group_filter_path(entity, status: 'active') do
          Active
      %li{class: ("active" if params[:status] == 'closed')}
        = link_to group_filter_path(entity, status: 'closed') do
          Closed
      %li{class: ("active" if params[:status] == 'all')}
        = link_to group_filter_path(entity, status: 'all') do
          All

app/views/groups/_new_group_member.html.haml
= form_for @users_group, url: group_group_members_path(@group), html: { class: 'form-horizontal users-group-form' } do |f|
  .form-group
    = f.label :user_ids, "People", class: 'control-label'
    .col-sm-10= users_select_tag(:user_ids, multiple: true, class: 'input-large')

  .form-group
    = f.label :access_level, "Group Access", class: 'control-label'
    .col-sm-10= select_tag :access_level, options_for_select(GroupMember.access_level_roles, @users_group.access_level), class: "project-access-select select2"

  .form-actions
    = f.submit 'Add users into group', class: "btn btn-create"

app/views/groups/_projects.html.haml
.panel.panel-default
  .panel-heading
    Projects (#{projects.count})
    - if can? current_user, :create_projects, @group
      .panel-head-actions
        = link_to new_project_path(namespace_id: @group.id), class: "btn btn-new" do
          %i.fa.fa-plus
          New project
  %ul.well-list
    - if projects.blank?
      .nothing-here-block This group has no projects yet
    - projects.each do |project|
      %li.project-row
        = link_to project_path(project), class: dom_class(project) do
          .dash-project-access-icon
            = visibility_level_icon(project.visibility_level)
          %span.str-truncated
            %span.project-name
              = project.name
          %span.arrow
            %i.fa.fa-angle-right

app/views/groups/_settings_nav.html.haml
%ul.nav.nav-pills.nav-stacked.nav-stacked-menu
  = nav_link(path: 'groups#edit') do
    = link_to edit_group_path(@group) do
      %i.fa.fa-pencil-square-o
      Group
  = nav_link(path: 'groups#projects') do
    = link_to projects_group_path(@group) do
      %i.fa.fa-folder
      Projects

app/views/groups/edit.html.haml
.row
  .col-md-2
    = render 'settings_nav'
  .col-md-10
    .panel.panel-default
      .panel-heading
        %strong= @group.name
        group settings:
      .panel-body
        = form_for @group, html: { multipart: true, class: "form-horizontal" }, authenticity_token: true do |f|
          - if @group.errors.any?
            .alert.alert-danger
              %span= @group.errors.full_messages.first
          .form-group
            = f.label :name, class: 'control-label' do
              Group name
            .col-sm-10
              = f.text_field :name, placeholder: "Ex. OpenSource", class: "form-control left"

          .form-group.group-description-holder
            = f.label :description, "Details", class: 'control-label'
            .col-sm-10
              = f.text_area :description, maxlength: 250, class: "form-control js-gfm-input", rows: 4

          .form-group
            .col-sm-2
            .col-sm-10
              = image_tag group_icon(@group.to_param), alt: '', class: 'avatar s160'
              %p.light
                - if @group.avatar?
                  You can change your group avatar here
                - else
                  You can upload a group avatar here
              %a.choose-btn.btn.btn-small.js-choose-group-avatar-button
                %i.fa.fa-paperclip
                %span Choose File ...
              &nbsp;
              %span.file_name.js-avatar-filename File name...
              = f.file_field :avatar, class: "js-group-avatar-input hidden"
              .light The maximum file size allowed is 100KB.
              - if @group.avatar?
                %hr
                = link_to 'Remove avatar', group_avatar_path(@group.to_param), data: { confirm: "Group avatar will be removed. Are you sure?"}, method: :delete, class: "btn btn-remove btn-small remove-avatar"

          .form-actions
            = f.submit 'Save group', class: "btn btn-save"

    .panel.panel-danger
      .panel-heading Remove group
      .panel-body
        %p
          Removing group will cause all child projects and resources to be removed.
          %br
          %strong Removed group can not be restored!

        = link_to 'Remove Group', @group, data: {confirm: 'Removed group can not be restored! Are you sure?'}, method: :delete, class: "btn btn-remove"

app/views/groups/issues.html.haml
%h3.page-title
  Issues

%p.light
  Only issues from
  %strong #{@group.name}
  group are listed here.
  - if current_user
    To see all issues you should visit #{link_to 'dashboard', issues_dashboard_path} page.
%hr

.row
  .fixed.sidebar-expand-button.hidden-lg.hidden-md
    %i.fa.fa-list.fa-2x
  .col-md-3.responsive-side
    = render 'shared/filter', entity: 'issue'
  .col-md-9
    = render 'shared/issues'

app/views/groups/members.html.haml
- show_roles = should_user_see_group_roles?(current_user, @group)
%h3.page-title
  Group members
- if show_roles
  %p.light
    Members of group have access to all group projects.
    Read more about permissions
    %strong= link_to "here", help_page_path("permissions", "permissions"), class: "vlink"

%hr

.clearfix.js-toggle-container
  = form_tag members_group_path(@group), method: :get, class: 'form-inline member-search-form'  do
    .form-group
      = search_field_tag :search, params[:search], { placeholder: 'Find existing member by name', class: 'form-control search-text-input input-mn-300' }
    = submit_tag 'Search', class: 'btn'

  - if current_user && current_user.can?(:manage_group, @group)
    .pull-right
      = link_to '#', class: 'btn btn-new js-toggle-button' do
        Add members
        %i.fa.fa-chevron-down

    .js-toggle-content.hide.new-group-member-holder
      = render "new_group_member"

.panel.panel-default.prepend-top-20
  .panel-heading
    %strong #{@group.name}
    group members
    %small
      (#{@members.total_count})
  %ul.well-list
    - @members.each do |member|
      = render 'groups/group_members/group_member', member: member, show_roles: show_roles, show_controls: true
= paginate @members, theme: 'gitlab'

:coffeescript
  $('form.member-search-form').on 'submit', (event) ->
    event.preventDefault()
    Turbolinks.visit @.action + '?' + $(@).serialize()

app/views/groups/merge_requests.html.haml
%h3.page-title
  Merge Requests

%p.light
  Only merge requests from
  %strong #{@group.name}
  group are listed here.
  - if current_user
    To see all merge requests you should visit #{link_to 'dashboard', merge_requests_dashboard_path} page.
%hr
.row
  .fixed.sidebar-expand-button.hidden-lg.hidden-md
    %i.fa.fa-list.fa-2x
  .col-md-3.responsive-side
    = render 'shared/filter', entity: 'merge_request'
  .col-md-9
    = render 'shared/merge_requests'

app/views/groups/new.html.haml
= form_for @group, html: { class: 'group-form form-horizontal' } do |f|
  - if @group.errors.any?
    .alert.alert-danger
      %span= @group.errors.full_messages.first
  .form-group
    = f.label :name, class: 'control-label' do
      Group name
    .col-sm-10
      = f.text_field :name, placeholder: "Ex. OpenSource", class: "form-control", tabindex: 1, autofocus: true

  .form-group.group-description-holder
    = f.label :description, "Details", class: 'control-label'
    .col-sm-10
      = f.text_area :description, maxlength: 250, class: "form-control js-gfm-input", rows: 4, tabindex: 2

  .form-group.group-description-holder
    = f.label :avatar, "Group avatar", class: 'control-label'
    .col-sm-10
      %a.choose-btn.btn.btn-small.js-choose-group-avatar-button
        %i.fa.fa-paperclip
        %span Choose File ...
      &nbsp;
      %span.file_name.js-avatar-filename File name...
      = f.file_field :avatar, class: "js-group-avatar-input hidden"
      .light The maximum file size allowed is 100KB.

  .form-group
    .col-sm-2
    .col-sm-10
      %ul
        %li A group is a collection of several projects
        %li Groups are private by default
        %li Members of a group may only view projects they have permission to access
        %li Group project URLs are prefixed with the group namespace
        %li Existing projects may be moved into a group

  .form-actions
    = f.submit 'Create group', class: "btn btn-create", tabindex: 3

app/views/groups/projects.html.haml
.row
  .col-md-2
    = render 'settings_nav'
  .col-md-10
    .panel.panel-default
      .panel-heading
        %strong= @group.name
        projects:
        - if can? current_user, :manage_group, @group
          .panel-head-actions
            = link_to new_project_path(namespace_id: @group.id), class: "btn btn-new" do
              %i.fa.fa-plus
              New Project
      %ul.well-list
        - @projects.each do |project|
          %li
            .list-item-name
              = visibility_level_icon(project.visibility_level)
              %strong= link_to project.name_with_namespace, project
              %span.label.label-gray
                = repository_size(project)
            .pull-right
              = link_to 'Members', project_team_index_path(project), id: "edit_#{dom_id(project)}", class: "btn btn-small"
              = link_to 'Edit', edit_project_path(project), id: "edit_#{dom_id(project)}", class: "btn btn-small"
              = link_to 'Remove', project, data: { confirm: remove_project_message(project)}, method: :delete, class: "btn btn-small btn-remove"
        - if @projects.blank?
          .nothing-here-block This group has no projects yet

    = paginate @projects, theme: "gitlab"

app/views/groups/show.html.haml
.dashboard
  %section.activities.col-md-8.hidden-sm.hidden-xs
    - if current_user
      = render "events/event_last_push", event: @last_push
      = link_to dashboard_path, class: 'btn btn-tiny' do
        &larr; To dashboard
      &nbsp;
    %span.cgray
      Currently you are only seeing events from the
      = @group.name
      group
    %hr
    = render 'shared/event_filter'
    - if @events.any?
      .content_list
    - else
      .nothing-here-block Project activity will be displayed here
    = spinner
  %aside.side.col-md-4
    .light-well.append-bottom-20
      = image_tag group_icon(@group.path), class: "avatar s90"
      .clearfix.light
        %h3.page-title
          = @group.name
        - if @group.description.present?
          %p
            = escaped_autolink(@group.description)
    = render "projects", projects: @projects
    - if current_user
      .prepend-top-20
        = link_to group_path(@group, { format: :atom, private_token: current_user.private_token }), title: "Feed" do
          %strong
            %i.fa.fa-rss
            News Feed

    %hr
    = render 'shared/promo'