config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"
  get 'search/autocomplete' => "search#autocomplete", as: :search_autocomplete

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  # Get all keys of user
  get ':username.keys' => 'profiles/keys#get_keys' , constraints: { username: /.*/ }

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitlab_shell.repos_path,
    upload_pack:  Gitlab.config.gitlab_shell.upload_pack,
    receive_pack: Gitlab.config.gitlab_shell.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }, via: [:get, :post]

  #
  # Help
  #

  get 'help'                  => 'help#index'
  get 'help/:category/:file'  => 'help#show', as: :help_page
  get 'help/shortcuts'

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Explroe area
  #
  namespace :explore do
    resources :projects, only: [:index] do
      collection do
        get :trending
        get :starred
      end
    end

    resources :groups, only: [:index]
    root to: "projects#trending"
  end

  # Compatibility with old routing
  get 'public' => "explore/projects#index"
  get 'public/projects' => "explore/projects#index"

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :team_update
        put :block
        put :unblock
        delete 'remove/:email_id', action: 'remove_email', as: 'remove_email'
      end
    end

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_teams_update
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resources :broadcast_messages, only: [:index, :create, :destroy]
    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]

    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do
      member do
        put :transfer
      end
    end

    root to: "dashboard#index"
  end

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :history
      get :design

      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :account, only: [:show, :update]
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create, :edit, :update] do
        member do
          put :reset
        end
      end
      resources :keys
      resources :emails, only: [:index, :create, :destroy]
      resources :groups, only: [:index] do
        member do
          delete :leave
        end
      end
      resource :avatar, only: [:destroy]
    end
  end

  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }, via: :get

  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard", only: [:show] do
    member do
      get :projects
      get :issues
      get :merge_requests
    end
  end

  #
  # Groups Area
  #
  resources :groups, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}  do
    member do
      get :issues
      get :merge_requests
      get :members
      get :projects
    end

    scope module: :groups do
      resources :group_members, only: [:create, :update, :destroy]
      resource :avatar, only: [:destroy]
      resources :milestones
    end
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations , passwords: :passwords, sessions: :sessions, confirmations: :confirmations }

  devise_scope :user do
    get "/users/auth/:provider/omniauth_error" => "omniauth_callbacks#omniauth_error", as: :omniauth_error
  end
  #
  # Project Area
  #
  resources :projects, constraints: { id: /[a-zA-Z.0-9_\-]+\/[a-zA-Z.0-9_\-]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      put :transfer
      post :fork
      post :archive
      post :unarchive
      post :upload_image
      post :toggle_star
      get :autocomplete_sources
      get :import
      put :retry_import
    end

    scope module: :projects do
      resources :blob, only: [:show, :destroy], constraints: { id: /.+/ } do
        get :diff, on: :member
      end
      resources :raw,       only: [:show], constraints: {id: /.+/}
      resources :tree,      only: [:show], constraints: {id: /.+/, format: /(html|js)/ }
      resources :edit_tree, only: [:show, :update], constraints: { id: /.+/ }, path: 'edit' do
        post :preview, on: :member
      end
      resources :new_tree,  only: [:show, :update], constraints: {id: /.+/}, path: 'new'
      resources :commit,    only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
      resources :commits,   only: [:show], constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}
      resources :compare,   only: [:index, :create]
      resources :blame,     only: [:show], constraints: {id: /.+/}
      resources :network,   only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
      resources :graphs,    only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/} do
        member do
          get :commits
        end
      end

      match "/compare/:from...:to" => "compare#show", as: "compare", via: [:get, :post], constraints: {from: /.+/, to: /.+/}

        resources :snippets, constraints: {id: /\d+/} do
          member do
            get "raw"
          end
        end

      resources :wikis, only: [:show, :edit, :destroy, :create], constraints: {id: /[a-zA-Z.0-9_\-\/]+/} do
        collection do
          get :pages
          put ':id' => 'wikis#update'
          get :git_access
        end

        member do
          get "history"
        end
      end

      resource :repository, only: [:show] do
        member do
          get "archive", constraints: { format: Gitlab::Regex.archive_formats_regex }
        end
      end

      resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
        member do
          get :test
        end
      end

      resources :deploy_keys, constraints: {id: /\d+/} do
        member do
          put :enable
          put :disable
        end
      end

      resources :branches, only: [:index, :new, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex }
      resources :tags, only: [:index, :new, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex }
      resources :protected_branches, only: [:index, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex }

      resources :refs, only: [] do
        collection do
          get "switch"
        end

        member do
          # tree viewer logs
          get "logs_tree", constraints: { id: Gitlab::Regex.git_reference_regex }
          get "logs_tree/:path" => "refs#logs_tree",
            as: :logs_file,
            constraints: {
              id:   Gitlab::Regex.git_reference_regex,
              path: /.*/
            }
        end
      end

      resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
        member do
          get :diffs
          post :automerge
          get :automerge_check
          get :ci_status
        end

        collection do
          get :branch_from
          get :branch_to
          get :update_branches
        end
      end

      resources :hooks, only: [:index, :create, :destroy], constraints: {id: /\d+/} do
        member do
          get :test
        end
      end

      resources :team, controller: 'team_members', only: [:index]
      resources :milestones, except: [:destroy], constraints: {id: /\d+/} do
        member do
          put :sort_issues
          put :sort_merge_requests
        end
      end

      resources :labels, constraints: {id: /\d+/} do
        collection do
          post :generate
        end
      end

      resources :issues, constraints: {id: /\d+/}, except: [:destroy] do
        collection do
          post  :bulk_update
        end
      end

      resources :team_members, except: [:index, :edit], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ } do
        collection do
          delete :leave

          # Used for import team
          # from another project
          get :import
          post :apply_import
        end
      end

      resources :notes, only: [:index, :create, :destroy, :update], constraints: {id: /\d+/} do
        member do
          delete :delete_attachment
        end

        collection do
          post :preview
        end
      end
    end
  end

  get ':id' => "namespaces#show", constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}

  root to: "dashboard#show"
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_filter :project, only: [:show, :transfer]
  before_filter :group, only: [:show, :transfer]
  before_filter :repository, only: [:show, :transfer]

  def index
    @projects = Project.all
    @projects = @projects.where(namespace_id: params[:namespace_id]) if params[:namespace_id].present?
    @projects = @projects.where("visibility_level IN (?)", params[:visibility_levels]) if params[:visibility_levels].present?
    @projects = @projects.with_push if params[:with_push].present?
    @projects = @projects.abandoned if params[:abandoned].present?
    @projects = @projects.search(params[:name]) if params[:name].present?
    @projects = @projects.sort(@sort = params[:sort])
    @projects = @projects.includes(:namespace).order("namespaces.path, projects.name ASC").page(params[:page]).per(20)
  end

  def show
    if @group
      @group_members = @group.members.order("access_level DESC").page(params[:group_members_page]).per(30)
    end

    @project_members = @project.project_members.page(params[:project_members_page]).per(30)
  end

  def transfer
    ::Projects::TransferService.new(@project, current_user, params.dup).execute

    redirect_to [:admin, @project.reload]
  end

  protected

  def project
    id = params[:project_id] || params[:id]

    @project = Project.find_with_namespace(id)
    @project || render_404
  end

  def group
    @group ||= project.group
  end

  def repository
    @repository ||= project.repository
  end
end

app/controllers/explore/projects_controller.rb
class Explore::ProjectsController < ApplicationController
  skip_before_filter :authenticate_user!,
    :reject_blocked,
    :add_abilities

  layout 'explore'

  def index
    @projects = ProjectsFinder.new.execute(current_user)
    @projects = @projects.search(params[:search]) if params[:search].present?
    @projects = @projects.sort(@sort = params[:sort])
    @projects = @projects.includes(:namespace).page(params[:page]).per(20)
  end

  def trending
    @trending_projects = TrendingProjectsFinder.new.execute(current_user)
    @trending_projects = @trending_projects.page(params[:page]).per(10)
  end

  def starred
    @starred_projects = ProjectsFinder.new.execute(current_user)
    @starred_projects = @starred_projects.order('star_count DESC')
    @starred_projects = @starred_projects.page(params[:page]).per(10)
  end
end

app/controllers/projects/application_controller.rb
class Projects::ApplicationController < ApplicationController
  before_filter :project
  before_filter :repository
  layout :determine_layout

  def authenticate_user!
    # Restrict access to Projects area only
    # for non-signed users
    if !current_user
      id = params[:project_id] || params[:id]
      @project = Project.find_with_namespace(id)

      return if @project && @project.public?
    end

    super
  end

  def determine_layout
    if current_user
      'projects'
    else
      'public_projects'
    end
  end

  def require_branch_head
    unless @repository.branch_names.include?(@ref)
      redirect_to project_tree_path(@project, @ref), notice: "This action is not allowed unless you are on top of a branch"
    end
  end
end

app/controllers/projects/base_tree_controller.rb
class Projects::BaseTreeController < Projects::ApplicationController
  include ExtractsPath

  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project
end

app/controllers/projects/blame_controller.rb
# Controller for viewing a file's blame
class Projects::BlameController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @blob = @repository.blob_at(@commit.id, @path)
    @blame = Gitlab::Git::Blame.new(project.repository, @commit.id, @path)
  end
end

app/controllers/projects/blob_controller.rb
# Controller for viewing a file's blame
class Projects::BlobController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project
  before_filter :authorize_push!, only: [:destroy]

  before_filter :blob

  def show
  end

  def destroy
    result = Files::DeleteService.new(@project, current_user, params, @ref, @path).execute

    if result[:status] == :success
      flash[:notice] = "Your changes have been successfully committed"
      redirect_to project_tree_path(@project, @ref)
    else
      flash[:alert] = result[:message]
      render :show
    end
  end

  def diff
    @form = UnfoldForm.new(params)
    @lines = @blob.data.lines[@form.since - 1..@form.to - 1]

    if @form.bottom?
      @match_line = ''
    else
      lines_length = @lines.length - 1
      line = [@form.since, lines_length].join(',')
      @match_line = "@@ -#{line}+#{line} @@"
    end

    render layout: false
  end

  private

  def blob
    @blob ||= @repository.blob_at(@commit.id, @path)

    if @blob
      @blob
    elsif tree.entries.any?
      redirect_to project_tree_path(@project, File.join(@ref, @path)) and return
    else
      return not_found!
    end
  end
end

app/controllers/projects/branches_controller.rb
class Projects::BranchesController < Projects::ApplicationController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :require_non_empty_project

  before_filter :authorize_code_access!
  before_filter :authorize_push!, only: [:create, :destroy]

  def index
    @sort = params[:sort] || 'name'
    @branches = @repository.branches_sorted_by(@sort)
    @branches = Kaminari.paginate_array(@branches).page(params[:page]).per(30)
  end

  def recent
    @branches = @repository.recent_branches
  end

  def create
    result = CreateBranchService.new(project, current_user).
        execute(params[:branch_name], params[:ref])
    if result[:status] == :success
      @branch = result[:branch]
      redirect_to project_tree_path(@project, @branch.name)
    else
      @error = result[:message]
      render action: 'new'
    end
  end

  def destroy
    DeleteBranchService.new(project, current_user).execute(params[:id])
    @branch_name = params[:id]

    respond_to do |format|
      format.html { redirect_to project_branches_path(@project) }
      format.js
    end
  end
end

app/controllers/projects/commit_controller.rb
# Controller for a specific Commit
#
# Not to be confused with CommitsController, plural.
class Projects::CommitController < Projects::ApplicationController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project
  before_filter :commit

  def show
    return git_not_found! unless @commit

    @line_notes = project.notes.for_commit_id(commit.id).inline
    @branches = project.repository.branch_names_contains(commit.id)
    @diffs = @commit.diffs
    @note = project.build_commit_note(commit)
    @notes_count = project.notes.for_commit_id(commit.id).count
    @notes = project.notes.for_commit_id(@commit.id).not_inline.fresh
    @noteable = @commit
    @comments_allowed = @reply_allowed = true
    @comments_target  = {
      noteable_type: 'Commit',
      commit_id: @commit.id
    }

    respond_to do |format|
      format.html
      format.diff  { render text: @commit.to_diff }
      format.patch { render text: @commit.to_patch }
    end
  end

  def commit
    @commit ||= project.repository.commit(params[:id])
  end
end

app/controllers/projects/commits_controller.rb
require "base64"

class Projects::CommitsController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @repo = @project.repository
    @limit, @offset = (params[:limit] || 40), (params[:offset] || 0)

    @commits = @repo.commits(@ref, @path, @limit, @offset)
    @note_counts = Note.where(commit_id: @commits.map(&:id)).
        group(:commit_id).count

    respond_to do |format|
      format.html
      format.json { pager_json("projects/commits/_commits", @commits.size) }
      format.atom { render layout: false }
    end
  end
end

app/views/admin/projects/index.html.haml
.row
  .col-md-3
    .admin-filter
      = form_tag admin_projects_path, method: :get, class: '' do
        .form-group
          = label_tag :name, 'Name:'
          = text_field_tag :name, params[:name], class: "form-control"

        .form-group
          = label_tag :namespace_id, "Namespace"
          = namespace_select_tag :namespace_id, selected: params[:namespace_id], class: 'input-large'

        .form-group
          %strong Activity
          .checkbox
            = label_tag :with_push, 'Not empty'
            = check_box_tag :with_push, 1, params[:with_push]
            &nbsp;
            %span.light Projects with push events
          .checkbox
            = label_tag :abandoned, 'Abandoned'
            = check_box_tag :abandoned, 1, params[:abandoned]
            &nbsp;
            %span.light No activity over 6 month

        %fieldset
          %strong Visibility level:
          .visibility-levels
            - Project.visibility_levels.each do |label, level|
              .checkbox
                %label
                  = check_box_tag 'visibility_levels[]', level, params[:visibility_levels].present? && params[:visibility_levels].include?(level.to_s)
                  %span.descr
                    = visibility_level_icon(level)
                    = label
        %hr
        = hidden_field_tag :sort, params[:sort]
        = submit_tag "Search", class: "btn submit btn-primary"
        = link_to "Reset", admin_projects_path, class: "btn btn-cancel"

  .col-md-9
    .panel.panel-default
      .panel-heading
        Projects (#{@projects.total_count})
        .panel-head-actions
          .dropdown.inline
            %a.dropdown-toggle.btn{href: '#', "data-toggle" => "dropdown"}
              %span.light sort:
              - if @sort.present?
                = @sort.humanize
              - else
                Name
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to admin_projects_path(sort: nil) do
                  Name
                = link_to admin_projects_path(sort: 'newest') do
                  Newest
                = link_to admin_projects_path(sort: 'oldest') do
                  Oldest
                = link_to admin_projects_path(sort: 'recently_updated') do
                  Recently updated
                = link_to admin_projects_path(sort: 'last_updated') do
                  Last updated
                = link_to admin_projects_path(sort: 'largest_repository') do
                  Largest repository
          = link_to 'New Project', new_project_path, class: "btn btn-new"
      %ul.well-list
        - @projects.each do |project|
          %li
            .list-item-name
              %span{ class: visibility_level_color(project.visibility_level) }
                = visibility_level_icon(project.visibility_level)
              = link_to project.name_with_namespace, [:admin, project]
            .pull-right
              %span.label.label-gray
                = repository_size(project)
              = link_to 'Edit', edit_project_path(project), id: "edit_#{dom_id(project)}", class: "btn btn-small"
              = link_to 'Destroy', [project], data: { confirm: remove_project_message(project) }, method: :delete, class: "btn btn-small btn-remove"
        - if @projects.blank?
          .nothing-here-block 0 projects matches
    = paginate @projects, theme: "gitlab"

app/views/admin/projects/show.html.haml
%h3.page-title
  Project: #{@project.name_with_namespace}
  = link_to edit_project_path(@project), class: "btn pull-right" do
    %i.fa.fa-pencil-square-o
    Edit
%hr
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        Project info:
      %ul.well-list
        %li
          %span.light Name:
          %strong
            = link_to @project.name, project_path(@project)
        %li
          %span.light Namespace:
          %strong
            - if @project.namespace
              = link_to @project.namespace.human_name, [:admin, @project.group || @project.owner]
            - else
              Global
        %li
          %span.light Owned by:
          %strong
            - if @project.owner
              = link_to @project.owner_name, [:admin, @project.owner]
            - else
              (deleted)

        %li
          %span.light Created by:
          %strong
            = @project.creator.try(:name) || '(deleted)'

        %li
          %span.light Created on:
          %strong
            = @project.created_at.stamp("March 1, 1999")

        %li
          %span.light http:
          %strong
            = link_to @project.http_url_to_repo
        %li
          %span.light ssh:
          %strong
            = link_to @project.ssh_url_to_repo
        - if @project.repository.exists?
          %li
            %span.light fs:
            %strong
              = @repository.path_to_repo

          %li
            %span.light Size
            %strong
              = repository_size(@project)

          %li
            %span.light last commit:
            %strong
              = last_commit(@project)
        - else
          %li
            %span.light repository:
            %strong.cred
              does not exist

        %li
          %span.light access:
          %strong
            %span{ class: visibility_level_color(@project.visibility_level) }
              = visibility_level_icon(@project.visibility_level)
              = visibility_level_label(@project.visibility_level)

    .panel.panel-default
      .panel-heading
        Transfer project
      .panel-body
        = form_for @project, url: transfer_admin_project_path(@project), method: :put, html: { class: 'form-horizontal' } do |f|
          .form-group
            = f.label :namespace_id, "Namespace", class: 'control-label'
            .col-sm-10
              = namespace_select_tag :namespace_id, selected: params[:namespace_id], class: 'input-large'

          .form-group
            .col-sm-2
            .col-sm-10
              = f.submit 'Transfer', class: 'btn btn-primary'

  .col-md-6
    - if @group
      .panel.panel-default
        .panel-heading
          %strong #{@group.name}
          group members (#{@group.group_members.count})
          .pull-right
            = link_to admin_group_path(@group), class: 'btn btn-small' do
              %i.fa.fa-pencil-square-o
        %ul.well-list
          - @group_members.each do |member|
            = render 'groups/group_members/group_member', member: member, show_controls: false
        .panel-footer
          = paginate @group_members, param_name: 'group_members_page', theme: 'gitlab'

    .panel.panel-default
      .panel-heading
        Project members
        %small
          (#{@project.users.count})
        .pull-right
          = link_to project_team_index_path(@project), class: "btn btn-tiny" do
            %i.fa.fa-pencil-square-o
            Manage Access
      %ul.well-list.team_members
        - @project_members.each do |project_member|
          - user = project_member.user
          %li.project_member
            .list-item-name
              %strong
                = link_to user.name, admin_user_path(user)
            .pull-right
              - if project_member.owner?
                %span.light Owner
              - else
                %span.light= project_member.human_access
                = link_to project_team_member_path(@project, user), data: { confirm: remove_from_project_team_message(@project, user)}, method: :delete, remote: true, class: "btn btn-small btn-remove" do
                  %i.fa.fa-times
      .panel-footer
        = paginate @project_members, param_name: 'project_members_page', theme: 'gitlab'